### ISSUE TITLE
Dependency constraint issue

### ISSUE THREAD

**Issue by PassKit** [VirtusLab/crypt#12]
You have a the following constraint in your Gopkg.toml

```toml
[[constraint]]
  name = "google.golang.org/api"
  branch = "master"
```

Please could you update this to a tagged version as this caused unresolvable conflicts when working with other projects that import this package.
